# Configurations
title:            XRD Dev Blog
longtitle:        XR Development Dev Blog
author:           
email:            
description: >

version:          1.0
gitbook_version:  3.2.3

url:              ''
baseurl:          '/xrdDevBlog'
rss:              RSS